### ISSUE TITLE
Musixmatch empty lyrics

### ISSUE THREAD

**Issue by EXTVoid** [Lambada10/SongSync#105]
**Describe the bug**
Musixmatch provider not showing `This track has no lyrics`

**Screenshots**
Here's the screenshot of two provider's
apple music and musixmatch
![IMG_20241102_214915](https://github.com/user-attachments/assets/a603ed15-38f2-4b6d-b3be-40b67c40ee98)

musixmatch raw request with empty lyrics response
![Screenshot_20241102-213128_1](https://github.com/user-attachments/assets/006553b6-bbc5-4296-9643-80bb15cf334e)

**Comment by kerollosy** [comment]
Apparently, this song's lyrics isn't available in USA for some reason so i updated the server settings so that the function runs from a different region (Germany instead of the USA)
Also, now if a song is restricted it will show `This track has no lyrics` instead of returning empty lyrics

Let me know if it’s working better
