### ISSUE TITLE
add Genius to search for letters

### ISSUE THREAD

**Issue by geniosoys** [Lambada10/SongSync#106]
Most of the music I listen to is in Spanish and there are not many synchronized lyrics, so many times I download unsynchronized lyrics. The most used song base in Spanish is Genius but your great application doesn't have it. The only application that works but has not been updated for a long time is the following one:

https://github.com/TecCheck/FastLyrics

I would be very grateful with this function if you can.

**Comment by letradeno** [comment]
to complement since it is so complicated to find letters in Spanish it would be essential to add the following, with these it would not be possible to improve:

**Bandcamp**
[https://bandcamp.com/search?q={artist}%20{title}&item_type=t](url)
most of the bands publish their lyrics on bandcamp

**Viasona**
[https://www.viasona.cat/grup](url)
the only site that collects songs in a little known language of spain from catalunya.

**Letras**
[https://www.letras.com](url)
page with the largest number of lyrics in spanish.

**Versos [Perfectos**]
[http://versosperfectos.com/discos](url)
page with the lyrics of spanish hihpop groups and the only way to find them.

To see how these filters work there is a musicbee plugin that has almost all of them:
[https://getmusicbee.com/forum/index.php?topic=36952.0](url)

**Comment by Lambada10** [comment]
Genius does not provide synced lyrics
