### ISSUE TITLE
the artist name section doesn't work

### ISSUE THREAD

**Issue by Umbras13** [Lambada10/SongSync#117]
**Describe the bug**
whenever i search for a lyric to a song it oftens get the wrong song, often for a different artist even tough the artist name has the correct, altough if i put the name of the artist/band it works as expected

**To Reproduce**
Steps to reproduce the behavior (with the song forest as an example):
1. go on the song selection page with all the songs downloaded
2. Click on the song "forest" by system of a down
3. it shows a song that is entirely unrelated
4. put the band name in the song title
5. it then works as expected, showing forest by system of a down

**Expected behavior**
it should filter to show lirycs from the band/artist of the song you selected, instead of having no effect

**Screenshots**
![Screenshot_2024-12-02-11-38-47-347_pl lambada songsync](https://github.com/user-attachments/assets/532bbc3e-a4b5-485c-8722-0a3508f81e70)
![Screenshot_2024-12-02-11-38-50-551_pl lambada songsync](https://github.com/user-attachments/assets/85b971e6-6eaa-46a2-a028-91f041a0fc93)
![Screenshot_2024-12-02-11-39-02-697_pl lambada songsync](https://github.com/user-attachments/assets/7247450d-46c5-4465-bd06-f9d25f179e85)
![Screenshot_2024-12-02-11-39-07-814_pl lambada songsync](https://github.com/user-attachments/assets/9b78dd6b-b24e-4795-a719-05cabfe4bd4d)

**Smartphone (please complete the following information):**
 - Device: Poco x3 pro
 - OS: MIUI 14 (android 13)
 - App version 4.2.1

**Comment by BobbyESP** [comment]
This is not an issue of the app but the provider. Anyways we will take a look at what we can do. @Lambada10

**Comment by kerollosy** [comment]
I'm guessing that the provider is LRCLib, because the current impl searches using the song name only: https://github.com/Lambada10/SongSync/blob/99785b8f552c908731801964be63ef9afb7744f2/app/src/main/java/pl/lambada/songsync/data/remote/lyrics_providers/others/LRCLibAPI.kt#L24-L29

I tried to use the api with the song name and artist separated by a space and it worked fine, maybe it should be updated to include the artist name
or we could use `track_name` and `artist_name` parameters (instead of `q`) in the api search for more accurate results

I can make a PR if you want me to

**Comment by Lambada10** [comment]
I completely forgot about that part, I'll revert it
